### ISSUE TITLE
Can  you  explain the meaning  of value  'data' in out.json?

### ISSUE THREAD

**Issue by qxang** [danwild/wind-js-server#1]
[{"header":{"discipline":0,"disciplineName":"Meteorological products","gribEdition":2,"gribLength":49047,"center":7,"centerName":"US National Weather Service ,"data":[253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253.8,253]}]?

**Comment by schlunsen** [comment]
Or can you explain how to retrieve data from NOAA?

**Comment by danwild** [comment]
**header** and **data** are the two main components of the [GRIB](https://en.wikipedia.org/wiki/GRIB) format, in which the **data** array represents a 2D grid of values.

The actual json you are referring to is produced by [grib2json](https://github.com/cambecc/grib2json).
