### ISSUE TITLE
No wind data

### ISSUE THREAD

**Issue by kaifaty** [danwild/wind-js-server#2]
It's arror 

> no wind data

 show after change demo.json to converted json from [NOAA this file](http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl?file=gfs.t18z.pgrb2.1p00.f000&lev_10_m_above_ground=on&var_UGRD=on&var_VGRD=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fgfs.2017011218) by `grib2json -d -n -o demo.json gfs.t18z.pgrb2.1p00.f000` command

**Comment by danwild** [comment]
Hi, what does the JSON output look like from your conversion? 
Does it have the same structure as the provided example [out.json](https://raw.githubusercontent.com/danwild/wind-js-server/master/converter/demo/out.json)?

**Comment by kaifaty** [comment]
Oh, I've got my problem solved. 
I didn't put "surface" and "TMP" in URL. 
[The URL need](http://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_1p00.pl?file=gfs.t18z.pgrb2.1p00.f000&lev_10_m_above_ground=on&lev_surface=on&var_TMP=on&var_UGRD=on&var_VGRD=on&leftlon=0&rightlon=360&toplat=90&bottomlat=-90&dir=%2Fgfs.2017011818)
