### ISSUE TITLE
Explanation on Grib2 Request information

### ISSUE THREAD

**Issue by mickeyjohn** [danwild/wind-js-server#6]
Hi,

Can you explain how do build the grib2 request parameters? It is best if you could provide the reference documentation. 
The server run well with leaflet-velocity. Actually what I trying to do is including more forcast info such as temperature, humidity, pressure,..
I found some infomation here: http://nomads.ncep.noaa.gov/ and http://www.nco.ncep.noaa.gov/pmb/products/gfs/gfs.t00z.pgrb2.1p00.f000.shtml but still not sure how to select the right parameters to obtain the additional data.

Thank you very much,
John

**Comment by danwild** [comment]
As mentioned in the [README](https://github.com/danwild/wind-js-server/blob/master/README.md), this project is only intended as a simple demo for how you might create your own grib data service.

If you're interested in how the requests are being built, you should look at what the code is doing - e.g. in the [getGribData](https://github.com/danwild/wind-js-server/blob/master/app.js#L156) function (note the `var_*` params).
